# Generated by Django 4.2.14 on 2024-07-16 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ProductID', models.BigIntegerField(unique=True)),
                ('ProductCode', models.CharField(max_length=255, unique=True)),
                ('ProductName', models.CharField(max_length=255)),
                ('ProductImage', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='uploads/')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDate', models.DateTimeField(blank=True, null=True)),
                ('IsFavourite', models.BooleanField(default=False)),
                ('Active', models.BooleanField(default=True)),
                ('HSNCode', models.CharField(blank=True, max_length=255, null=True)),
                ('TotalStock', models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True)),
                ('CreatedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user%(class)s_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'products_product',
                'ordering': ('-CreatedDate', 'ProductID'),
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='stocks.products')),
            ],
        ),
        migrations.CreateModel(
            name='SubVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock', models.DecimalField(decimal_places=8, default=0.0, max_digits=20)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subvariants', to='stocks.variant')),
            ],
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product', 'name', 'option'], name='stocks_vari_product_1a767a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'name', 'option')},
        ),
        migrations.AddIndex(
            model_name='subvariant',
            index=models.Index(fields=['variant', 'name'], name='stocks_subv_variant_604937_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subvariant',
            unique_together={('variant', 'name')},
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['ProductName'], name='products_pr_Product_c58fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['CreatedDate'], name='products_pr_Created_86f0b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('ProductCode', 'ProductID')},
        ),
    ]
