# Generated by Django 4.2.14 on 2024-07-16 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subvariant',
            name='stocks_subv_variant_604937_idx',
        ),
        migrations.AlterUniqueTogether(
            name='subvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subvariant',
            name='variant_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subvariants_color', to='stocks.variant'),
        ),
        migrations.AddField(
            model_name='subvariant',
            name='variant_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subvariants_size', to='stocks.variant'),
        ),
        migrations.AlterUniqueTogether(
            name='subvariant',
            unique_together={('variant_color', 'variant_size', 'name')},
        ),
        migrations.AddIndex(
            model_name='subvariant',
            index=models.Index(fields=['variant_color', 'variant_size', 'name'], name='stocks_subv_variant_289ee4_idx'),
        ),
        migrations.RemoveField(
            model_name='subvariant',
            name='variant',
        ),
    ]
