# Generated by Django 4.2.14 on 2024-07-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_subvariant_stocks_subv_variant_604937_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subvariant',
            name='stocks_subv_variant_289ee4_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='stocks_vari_product_1a767a_idx',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='name',
            new_name='variant_name',
        ),
        migrations.AlterUniqueTogether(
            name='subvariant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'variant_name')},
        ),
        migrations.AddField(
            model_name='subvariant',
            name='option',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subvariant',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subvariants', to='stocks.variant'),
        ),
        migrations.AlterField(
            model_name='subvariant',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subvariant',
            unique_together={('variant', 'option')},
        ),
        migrations.AddIndex(
            model_name='subvariant',
            index=models.Index(fields=['variant', 'option'], name='stocks_subv_variant_6a34b6_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product', 'variant_name'], name='stocks_vari_product_329056_idx'),
        ),
        migrations.RemoveField(
            model_name='subvariant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subvariant',
            name='variant_color',
        ),
        migrations.RemoveField(
            model_name='subvariant',
            name='variant_size',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='option',
        ),
    ]
