# Generated by Django 4.2.14 on 2024-07-17 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0003_remove_subvariant_stocks_subv_variant_289ee4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='CreatedUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user%(class)s_objects', to=settings.AUTH_USER_MODEL),
        ),
    ]
