# Generated by Django 4.2.14 on 2024-07-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_products_createduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='TotalStock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subvariant',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
