# Generated by Django 4.2.14 on 2024-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_products_totalstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='TotalStock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
